const fs = require('fs');
let cards = JSON.parse(fs.readFileSync('_cards.json'));
const batch = [
  {id:'pq561',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'A group of owls is called a parliament.',fact:'The collective noun for owls is a parliament, reflecting their association with wisdom in folklore. A group of owls roosting together is also sometimes called a wisdom. They are among the most adaptable birds.',tip:'🧠 Owls = parliament or wisdom. Reflects folklore association with wisdom and knowledge.'},
  {id:'pq562',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The word muscle comes from a word meaning little mouse.',fact:'Muscle derives from the Latin musculus meaning little mouse. Romans thought flexing muscles looked like mice moving under the skin. The word mussel for the shellfish has exactly the same Latin root.',tip:'🧠 Muscle: from Latin musculus = little mouse. Flexing looked like mice under skin. Mussel shares same root.'},
  {id:'pq563',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'Octopuses have three hearts.',fact:'Octopuses have three hearts: two branchial hearts pump blood through the gills and one systemic heart pumps oxygenated blood through the body. The systemic heart stops when the octopus swims, tiring them quickly.',tip:'🧠 Octopus: 3 hearts. Two for gills, one for body. Systemic heart stops during swimming = tires quickly.'},
  {id:'pq564',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The first commercial passenger jet service began in 1952.',fact:'The de Havilland Comet inaugurated the first scheduled commercial jet airline service on 2 May 1952 operated by BOAC between London and Johannesburg. It revolutionised air travel despite early fatal accidents.',tip:'🧠 First commercial jet service: de Havilland Comet, BOAC, 2 May 1952, London to Johannesburg.'},
  {id:'pq565',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'A group of butterflies is called a kaleidoscope.',fact:'The collective noun for butterflies is a kaleidoscope or a flutter. A group of caterpillars is called an army. Butterflies taste with their feet using taste sensors called chemoreceptors on their tarsi.',tip:'🧠 Butterflies = kaleidoscope or flutter. Taste with feet (chemoreceptors on tarsi). Caterpillars = army.'},
  {id:'pq566',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The Rosetta Stone is written in three scripts.',fact:'The Rosetta Stone contains the same priestly decree in three scripts: Ancient Egyptian hieroglyphics, Demotic script and Ancient Greek. Champollion used the Greek text to decode hieroglyphics in 1822.',tip:'🧠 Rosetta Stone: three scripts (hieroglyphics, Demotic, Greek). Champollion decoded hieroglyphics 1822 using Greek.'},
  {id:'pq567',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'Honeybees can recognise human faces.',fact:'Research shows honeybees can learn to identify human faces using the same holistic face-processing strategy humans use. They can be trained to associate faces with rewards in laboratory experiments.',tip:'🧠 Honeybees: can recognise human faces. Use holistic processing like humans. Trainable in laboratory experiments.'},
  {id:'s244',cat:'science',emoji:'🔬',subject:'Science',diff:1,hook:'Sound travels about 4 times faster in water than in air.',fact:'Sound travels at about 343 metres per second in air at 20 degrees Celsius but about 1480 metres per second in water. This is why whales can communicate across ocean basins.',tip:'🧠 Sound in water: 1480 m/s, about 4x faster than air (343 m/s). Enables whale communication across oceans.'},
  {id:'s245',cat:'science',emoji:'🧪',subject:'Science',diff:2,hook:'The periodic table was predicted to have gaps before those elements were found.',fact:'Dmitri Mendeleev published his periodic table in 1869 and left deliberate gaps for undiscovered elements. He predicted properties of gallium, germanium and scandium before they were found. All his predictions proved correct.',tip:'🧠 Mendeleev 1869: left gaps and predicted undiscovered elements. Gallium, germanium, scandium all confirmed correctly.'},
  {id:'h171',cat:'history',emoji:'📜',subject:'History',diff:1,hook:'The first moon landing was on 20 July 1969.',fact:'Apollo 11 landed on the Moon on 20 July 1969. Neil Armstrong became the first human to walk on the Moon at 02:56 UTC on 21 July. Buzz Aldrin followed. Michael Collins orbited above.',tip:'🧠 Moon landing: 20 July 1969, Apollo 11. Armstrong first to walk 02:56 UTC 21 July. Collins orbited above.'},
  {id:'h172',cat:'history',emoji:'⚔️',subject:'History',diff:2,hook:'The War of 1812 ended before America knew it had begun.',fact:'The British repealed the Orders in Council on 16 June 1812, the main US grievance, two days before the USA declared war on 18 June. News travelled too slowly. The war continued two more years unnecessarily.',tip:'🧠 War of 1812: British removed main US grievance 2 days before USA declared war. Slow communication caused 2 more years.'},
  {id:'geo161',cat:'geo',emoji:'🌍',subject:'Geography',diff:1,hook:'The worlds longest river is disputed between the Nile and Amazon.',fact:'The Nile has traditionally been considered the longest river at about 6,650 km. However some measurements of the Amazon with all tributaries suggest it may reach 6,800 km. The debate continues among geographers.',tip:'🧠 Longest river: disputed. Nile ~6,650 km. Amazon possibly ~6,800 km depending on measurement. Ongoing debate.'},
  {id:'b161',cat:'body',emoji:'🧠',subject:'Body',diff:1,hook:'The human brain contains about 86 billion neurons.',fact:'Neuroscientist Suzana Herculano-Houzel determined the human brain contains approximately 86 billion neurons using a cell-counting technique. Earlier estimates of 100 billion are considered too high.',tip:'🧠 Brain neurons: ~86 billion, not 100 billion as previously thought. Determined by Herculano-Houzel using cell counting.'},
  {id:'g126',cat:'grammar',emoji:'✍️',subject:'Grammar',diff:1,hook:'Verbs are the engine of every sentence.',fact:'Every sentence requires a verb. Verbs express action (run, think, decide), occurrence (happen, become) or state of being (is, seems, appears). Without a verb no sentence can be complete.',tip:'🧠 Verbs: required in every sentence. Express action (run), occurrence (happen) or being (is, seems).'},
  {id:'psy141',cat:'psychology',emoji:'🧠',subject:'Psychology',diff:1,hook:'People underestimate how much they will change in the future.',fact:'The end of history illusion (Quoidbach 2013): people recognise they have changed a lot in the past decade but believe they will change very little in the next decade. We see our current self as final.',tip:'🧠 End of history illusion: we know we changed in the past but think we have stopped changing now.'},
  {id:'eco121',cat:'economics',emoji:'💰',subject:'Economics',diff:1,hook:'Compound interest doubles money at a predictable rate.',fact:'The rule of 72: divide 72 by the annual interest rate to find years to double money. At 6 percent interest money doubles in 12 years. At 9 percent in 8 years. A quick mental arithmetic shortcut.',tip:'🧠 Rule of 72: divide 72 by interest rate = years to double. 72/6=12 years. 72/9=8 years.'},
  {id:'inv126',cat:'inventions',emoji:'💡',subject:'Inventions',diff:1,hook:'The light bulb was not invented by Thomas Edison alone.',fact:'Joseph Swan demonstrated a working incandescent bulb in Newcastle England in December 1878, months before Edison in 1879. Both received patents. They eventually merged their companies. Swan demonstrated first.',tip:'🧠 Light bulb: Swan demonstrated December 1878 in England, Edison 1879 in USA. Both patented. Companies merged.'},
];
cards = cards.concat(batch);
fs.writeFileSync('_cards.json', JSON.stringify(cards));
console.log('Total:', cards.length);
