const fs = require('fs');
let cards = JSON.parse(fs.readFileSync('_cards.json'));
const batch = [
  {id:'pq91',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'Elephants are the only animals that cannot jump.',fact:'Adult elephants are the only mammals physically incapable of jumping. Their bone structure and weight of up to 6 tonnes make it impossible. They can run 25 km/h but never go fully airborne.',tip:'🧠 Elephants: only mammals that cannot jump. Can run 25 km/h though.'},
  {id:'pq92',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'Nintendo was founded in 1889 as a playing card company.',fact:'Nintendo was founded 23 September 1889 in Kyoto making handcrafted Hanafuda playing cards. It did not enter video games until the 1970s. The company is over 130 years old.',tip:'🧠 Nintendo: founded 1889, made playing cards. Video games came 80 years later.'},
  {id:'pq93',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'The name Google was a spelling mistake.',fact:'The founders meant to name it Googol meaning 10 to the power of 100. Investor Sean Anderson misspelled it as Google when checking domain availability and the name stuck.',tip:'🧠 Google = accidental misspelling of Googol. The typo became a trillion dollar brand.'},
  {id:'pq94',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'More people die from vending machine accidents than shark attacks each year.',fact:'Vending machines kill approximately 13 people per year in the US from people rocking them to dislodge stuck items. Sharks kill 5 to 10 globally per year.',tip:'🧠 Vending machines kill more people per year than sharks. Choose your enemy wisely.'},
  {id:'pq95',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'It is impossible to hum while holding your nose closed.',fact:'Humming requires air to flow through the nasal passage. When you block the nose the sound cannot be produced. Try it right now.',tip:'🧠 Cannot hum with nose closed. Needs nasal airflow. Try it.'},
  {id:'pq96',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The Pacific Ocean is wider than the Moon.',fact:'The Pacific Ocean spans approximately 19,800 km at its widest. The Moon diameter is 3,474 km. The Pacific is about 5.7 times wider than the Moon.',tip:'🧠 Pacific width: 19,800 km. Moon diameter: 3,474 km. Pacific wins by 5.7 times.'},
  {id:'pq97',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'Butterflies taste with their feet.',fact:'Butterflies have chemoreceptors on their feet. When they land on a surface they immediately taste it, identifying food sources and suitable plants for laying eggs.',tip:'🧠 Butterflies taste with their feet. Chemoreceptors on their tarsi.'},
  {id:'pq98',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The inventor of the Frisbee was turned into a Frisbee after he died.',fact:'Walter Morrison invented the Frisbee in the 1940s. When he died in 2010 his family had his ashes mixed into a batch of Frisbees and distributed them to friends and family.',tip:'🧠 Frisbee inventor Walter Morrison: ashes turned into Frisbees after his death in 2010.'},
  {id:'pq99',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'A bolt of lightning could power a 100 watt bulb for 3 months.',fact:'A lightning bolt carries roughly 250 kWh of energy. A 100 watt bulb uses 2.4 kWh per day so one bolt equals about 104 days of light. Too fast to harvest though.',tip:'🧠 Lightning: 250 kWh per bolt. Enough for 3 months of a 100W bulb. Too fast to harvest.'},
  {id:'pq100',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'A cat has 32 muscles in each ear.',fact:'Cats have 32 muscles controlling each ear letting them rotate 180 degrees independently. Humans have about 6 ear muscles and mostly cannot move them at all.',tip:'🧠 Cats: 32 ear muscles each, rotate 180 degrees. Humans: 6, mostly useless.'},
  {id:'pq101',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The human body contains enough iron to make a 3 inch nail.',fact:'An adult body contains roughly 3 to 4 grams of iron, mostly in red blood cells as haemoglobin. That is enough iron to forge a small nail.',tip:'🧠 Body iron: 3 to 4 grams, enough for a 3 inch nail.'},
  {id:'pq102',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'Alaska is the most northern western and eastern US state simultaneously.',fact:'Alaska contains the westernmost point of the US and because the Aleutian Islands cross the 180 degree meridian, also the easternmost point. It is also the northernmost state.',tip:'🧠 Alaska: most northern, western AND eastern US state. Aleutians cross the date line.'},
  {id:'pq103',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'A group of cats is called a clowder.',fact:'The collective noun for cats is a clowder. A group of kittens is a kindle. A group of wild cats is a destruction.',tip:'🧠 Cats = clowder. Kittens = kindle. Wild cats = destruction.'},
  {id:'pq104',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'The hash symbol has a proper name called an octothorpe.',fact:'The hash symbol is officially called an octothorpe. Octo for its eight points. It was used on telephone keypads before Twitter made it globally famous in 2007.',tip:'🧠 The hash symbol = octothorpe. Eight points = octo. Twitter made it global in 2007.'},
  {id:'pq105',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'The first tweet was sent on 21 March 2006.',fact:'Jack Dorsey sent the first ever tweet saying just setting up my twttr on 21 March 2006. It later sold as an NFT for 2.9 million dollars.',tip:'🧠 First tweet: Jack Dorsey, 21 March 2006. Sold as NFT for 2.9 million dollars.'},
  {id:'pq106',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'Lobsters were once considered food fit only for prisoners.',fact:'In colonial New England lobsters were so abundant they washed ashore in piles. Laws were passed against feeding servants lobster more than 3 times a week. Now it is a luxury.',tip:'🧠 Lobster: once poor person food fed to prisoners. Now a luxury.'},
  {id:'pq107',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'The worlds oldest joke dates back to 1900 BC.',fact:'The oldest recorded joke comes from ancient Sumer around 1900 BC and is about flatulence. The second oldest from Egypt around 1600 BC is also scatological. Comedy is timeless.',tip:'🧠 Oldest joke: Sumerian, 1900 BC, about flatulence. Comedy has not changed much.'},
  {id:'pq108',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'A blue whale heart is so large a human could crawl through its arteries.',fact:'The blue whale heart weighs 180 kg and is the size of a small car. Its main aorta is wide enough for a human to crawl through. It beats 4 to 8 times per minute.',tip:'🧠 Blue whale heart: 180 kg, car-sized. Aorta wide enough to crawl through.'},
  {id:'pq109',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:2,hook:'Turtles can breathe through their rear ends.',fact:'Painted turtles absorb oxygen through their cloaca during winter hibernation. This lets them stay submerged under ice for months without breathing at all.',tip:'🧠 Turtles breathe through their cloaca in winter. Cloacal bursae respiration.'},
  {id:'pq110',cat:'pub',emoji:'🍺',subject:'Pub Quiz',diff:1,hook:'The longest English word using only the top keyboard row is typewriter.',fact:'The QWERTY top row contains Q W E R T Y U I O P. Typewriter uses only those 10 keys and is the longest common English word achievable this way.',tip:'🧠 Longest top-row-only word: TYPEWRITER. All 10 letters on the top row.'},
];
cards = cards.concat(batch);
fs.writeFileSync('_cards.json', JSON.stringify(cards));
console.log('Total:', cards.length);
