export const GRADS = [
  '#4d96ff','#ff6b6b','#20c997','#cc5de8',
  '#ff922b','#f06595','#38d9a9','#e67e22',
];

export const CAT_COLOR = {
  math: '#ffd93d', science: '#20c997', grammar: '#f06595',
  geo: '#ff922b', history: '#cc5de8', body: '#ff6b6b',
  psychology: '#4d96ff', economics: '#38d9a9',
  inventions: '#ff922b', food: '#f06595', pub: 'gold',
};

export const DIFF_LABELS = { 1: '⭐ Easy', 2: '⭐⭐ Medium', 3: '⭐⭐⭐ Hard' };

export const WOTD_LIST = [
  { word: 'Ephemeral', phonetic: '/ɪˈfem.ər.əl/', def: 'Lasting for only a short time; transitory.', example: '"The morning frost was ephemeral, gone by 9am."' },
  { word: 'Serendipity', phonetic: '/ˌser.ənˈdɪp.ɪ.ti/', def: 'The occurrence of fortunate events by chance.', example: '"Finding that €50 note was pure serendipity."' },
  { word: 'Sycophant', phonetic: '/ˈsɪk.ə.fənt/', def: 'A person who flatters powerful people to gain advantage.', example: '"The boardroom was full of sycophants who never challenged the CEO."' },
  { word: 'Ubiquitous', phonetic: '/juːˈbɪk.wɪ.təs/', def: 'Present, appearing, or found everywhere.', example: '"Smartphones are now ubiquitous — even in remote villages."' },
  { word: 'Pragmatic', phonetic: '/præɡˈmæt.ɪk/', def: 'Dealing with things sensibly and realistically.', example: '"She took a pragmatic approach — forget the plan, fix the problem."' },
  { word: 'Laconic', phonetic: '/ləˈkɒn.ɪk/', def: 'Using very few words; brief and concise.', example: '"His laconic reply — \'Fine\' — said everything and nothing."' },
  { word: 'Eloquent', phonetic: '/ˈel.ə.kwənt/', def: 'Fluent and persuasive in speaking or writing.', example: '"Her eloquent speech moved the entire audience to tears."' },
  { word: 'Nefarious', phonetic: '/nɪˈfeə.ri.əs/', def: 'Wicked, criminal, or villainous.', example: '"The nefarious scheme unravelled when someone talked."' },
  { word: 'Tenacious', phonetic: '/tɪˈneɪ.ʃəs/', def: 'Holding firmly to something; persistent and determined.', example: '"Her tenacious work ethic got her from intern to director in 4 years."' },
  { word: 'Candid', phonetic: '/ˈkæn.dɪd/', def: 'Truthful and straightforward, even if uncomfortable.', example: '"I appreciate candid feedback — tell me what\'s actually wrong."' },
  { word: 'Diligent', phonetic: '/ˈdɪl.ɪ.dʒənt/', def: 'Showing care and effort in work or duties.', example: '"The diligent student reviewed her notes every evening."' },
  { word: 'Gregarious', phonetic: '/ɡrɪˈɡeə.ri.əs/', def: 'Fond of company; sociable.', example: '"She was the most gregarious person at any party."' },
  { word: 'Frugal', phonetic: '/ˈfruː.ɡəl/', def: 'Economical with money; avoiding waste.', example: '"His frugal lifestyle meant he retired at 45."' },
  { word: 'Ambiguous', phonetic: '/æmˈbɪɡ.ju.əs/', def: 'Having more than one possible meaning; unclear.', example: '"The contract was ambiguous — both sides claimed to have won."' },
  { word: 'Erratic', phonetic: '/ɪˈræt.ɪk/', def: 'Not predictable; inconsistent in behaviour.', example: '"The erratic Wi-Fi made video calls impossible."' },
];

export const CARDS = [
  // PUB QUIZ
  { id: 'pq1', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "This country has won Eurovision more times than any other.", fact: "Ireland has won the Eurovision Song Contest 7 times — 1970, 1980, 1987, 1992, 1993, 1994, and 1996. Sweden is tied with 7 wins as of 2023. Ireland's three consecutive wins (1992–94) remain unmatched.", tip: "🧠 Ireland & Sweden lead Eurovision with 7 wins each. Ireland's hat-trick (1992–94) is the all-time record." },
  { id: 'pq2', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "The world's best-selling music artist of all time is not The Beatles.", fact: "Michael Jackson's Thriller (1982) is the best-selling album of all time at 66–70 million copies. The Beatles hold the record for best-selling band (~600 million records). Elvis Presley holds the record for most singles sold.", tip: "🧠 Best-selling album: Thriller. Best-selling band: Beatles. Most singles: Elvis. Three different records." },
  { id: 'pq3', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "Mount Everest is not the closest point on Earth to outer space.", fact: "Mount Chimborazo in Ecuador is the point on Earth's surface furthest from Earth's centre — and therefore closest to space — because Earth bulges at the equator. Everest is the highest above sea level (8,849m) but Chimborazo wins by ~2km of Earth-radius advantage.", tip: "🧠 Everest = highest above sea level. Chimborazo = furthest from Earth's centre. Two different records." },
  { id: 'pq4', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "This is the only country in the world with a non-rectangular flag.", fact: "Nepal is the only country with a non-quadrilateral flag. It's a double-pennant shape — two stacked triangles — making it unique among all 195 national flags. All other countries use rectangles or squares.", tip: "🧠 Nepal = only non-rectangular flag. The shape is a double-pennant. Perfect pub quiz gotcha." },
  { id: 'pq5', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "The Great Wall of China is not visible from space — this is one of history's most persistent myths.", fact: "The Great Wall is too narrow (5–8 metres wide) to be seen from orbit with the naked eye. Chinese astronaut Yang Liwei confirmed this in 2003. City lights and highways are actually visible from low orbit.", tip: "🧠 Great Wall from space = myth. It's wide enough to walk on but invisible at orbital distance." },
  { id: 'pq6', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "This tiny creature kills more humans every year than every large predator combined.", fact: "The mosquito kills approximately 725,000 people per year — the world's deadliest animal to humans. It transmits malaria, dengue, yellow fever, and Zika. Sharks kill fewer than 10 people per year.", tip: "🧠 Deadliest animal: mosquito (725,000/yr). Humans second (~475,000). Sharks: fewer than 10." },
  { id: 'pq7', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "Shakespeare invented over 1,700 words you still use every single day.", fact: "William Shakespeare coined or first recorded over 1,700 English words including 'bedroom', 'lonely', 'generous', 'swagger', 'uncomfortable', 'luggage', and 'eyeball'. He wrote 37 plays and 154 sonnets.", tip: "🧠 Shakespeare invented: bedroom, lonely, generous, swagger, eyeball, luggage. Next time you swagger, thank him." },
  { id: 'pq8', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "The Eiffel Tower is measurably taller in summer than in winter.", fact: "The Eiffel Tower grows up to 15cm taller in summer due to thermal expansion. Built in 1889 by Gustave Eiffel for the Paris World's Fair, it was originally intended to be demolished after 20 years. It was saved because it made a useful radio antenna.", tip: "🧠 Eiffel Tower: built 1889, grows 15cm in summer, was meant to be torn down. Radio saved it." },
  { id: 'pq9', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", fact: "Cleopatra VII ruled around 50 BC. The Great Pyramid was built around 2560 BC — 2,500 years before her. The Moon landing was 1969 AD — only ~2,000 years after Cleopatra. The pyramids are ancient even by ancient standards.", tip: "🧠 Pyramid → Cleopatra: 2,500 years. Cleopatra → Moon landing: ~2,000 years." },
  { id: 'pq10', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "A day on Venus is longer than a year on Venus.", fact: "Venus rotates so slowly that one Venusian day (243 Earth days) is longer than its year (225 Earth days). Venus also rotates backwards — the Sun rises in the west and sets in the east. It's the hottest planet despite Mercury being closer to the Sun.", tip: "🧠 Venus: day longer than year, Sun rises in the west, hottest planet. Three facts in one planet." },
  { id: 'pq11', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "The shortest war in history lasted less time than a football match.", fact: "The Anglo-Zanzibar War of 27 August 1896 lasted between 38 and 45 minutes — the shortest recorded war in history. Britain shelled the Sultan of Zanzibar's palace and won in under an hour. The Hundred Years' War actually lasted 116 years.", tip: "🧠 Shortest war: Anglo-Zanzibar, 1896, ~40 minutes. Longest: Hundred Years' War (116 years)." },
  { id: 'pq12', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "Honey found in Egyptian tombs 3,000 years old is still perfectly edible.", fact: "Honey never spoils when sealed and kept dry. Its low moisture, acidic pH, and natural hydrogen peroxide make it inhospitable to bacteria. Other foods with indefinite shelf life include salt, pure vanilla extract, white rice, and hard liquor.", tip: "🧠 Honey = infinite shelf life. Also: salt, white rice, hard liquor. All last forever if stored properly." },
  { id: 'pq13', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 1, hook: "Russia spans 11 time zones — the most of any country on Earth.", fact: "Russia covers 11 time zones and ~17.1 million km², making it the world's largest country. When it's 6am in Kaliningrad, it's already 5pm in Kamchatka. Canada is second largest but spans only 6 time zones.", tip: "🧠 Russia: largest country, 11 time zones. Canada: second largest, 6 time zones." },
  { id: 'pq14', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "The inventor of the telephone never called his wife or his mother — both were deaf.", fact: "Alexander Graham Bell patented the telephone in 1876. His mother and wife Mabel were both deaf, which drove his obsession with sound and communication. Bell considered the telephone an intrusion and refused to have one in his personal study.", tip: "🧠 Bell = telephone, 1876. Deaf family motivated him. Ironically disliked his own invention." },
  { id: 'pq15', cat: 'pub', emoji: '🍺', subject: 'Pub Quiz', diff: 2, hook: "This is the world's oldest airline, still flying today under its original name.", fact: "KLM Royal Dutch Airlines, founded in October 1919, is the world's oldest airline still operating under its original name. Qantas (Australia, 1920) is the second oldest.", tip: "🧠 Oldest airline: KLM, 1919, Netherlands. Second: Qantas, 1920, Australia." },

  // SCIENCE
  { id: 's1', cat: 'science', emoji: '⚗️', subject: 'Science — Chemistry', diff: 1, hook: "Everything you've ever touched is made of the same basic stuff.", fact: "All matter is made of atoms. Atoms bond to form molecules. Water (H₂O) is two hydrogen atoms bonded to one oxygen atom. There are 118 known elements in the periodic table.", tip: "🧠 H₂O: 2 Hydrogen + 1 Oxygen. The number after the letter = how many atoms of that element." },
  { id: 's2', cat: 'science', emoji: '⚡', subject: 'Science — Electricity', diff: 2, hook: "Your phone charger uses this law every second of every charge.", fact: "Ohm's Law: Voltage (V) = Current (I) × Resistance (R). Voltage is the push (volts). Current is the flow of electrons (amps). Resistance opposes the flow (ohms). Double resistance = half the current.", tip: "🧠 Water pipe: voltage = pressure, current = flow rate, resistance = pipe width. V=IR always." },
  { id: 's3', cat: 'science', emoji: '🧲', subject: 'Science — Magnetism', diff: 1, hook: "Earth itself is a giant magnet — and that's why navigation has worked for centuries.", fact: "Opposite magnetic poles attract; like poles repel — always. Earth has a magnetic north and south pole, slightly offset from geographic poles. A compass needle aligns with Earth's magnetic field. No magnet ever has only one pole.", tip: "🧠 Cut a magnet in half: you get two smaller magnets each with north and south. Monopoles don't exist." },
  { id: 's4', cat: 'science', emoji: '🌡️', subject: 'Science — Heat', diff: 2, hook: "The Sun heats Earth from 150 million km away — here's the mechanism.", fact: "Heat transfers three ways: conduction (direct contact — metal spoon in soup), convection (fluid movement — hot air rising), and radiation (electromagnetic waves — sunlight through space). Only radiation works in a vacuum.", tip: "🧠 CCR: Conduction=Contact, Convection=Currents, Radiation=Remote. Only radiation works in space." },
  { id: 's5', cat: 'science', emoji: '🧪', subject: 'Science — pH', diff: 1, hook: "Lemon juice and bleach are both liquids — but complete chemical opposites.", fact: "pH runs 0–14. Below 7 = acid (lemon ≈ 2, coffee ≈ 5). Above 7 = alkali (baking soda ≈ 9, bleach ≈ 13). Pure water = neutral 7. Human blood is maintained at pH 7.4 — even 0.1 deviation causes serious illness.", tip: "🧠 pH 7 = neutral. Stomach acid = pH 1.5. Blood = 7.4. Your body defends these numbers fiercely." },
  { id: 's6', cat: 'science', emoji: '🔬', subject: 'Science — Biology', diff: 1, hook: "Every living thing started as a single cell — from bacteria to blue whales.", fact: "All living organisms are made of cells. Plant cells have a rigid wall and chloroplasts enabling photosynthesis. Animal cells have neither. All cells contain DNA. The human body contains ~37 trillion cells.", tip: "🧠 37 trillion cells in your body. Plants have walls. Animals don't. Chloroplasts = why plants are green." },
  { id: 's7', cat: 'science', emoji: '🌊', subject: 'Science — Light & Sound', diff: 2, hook: "You always see lightning before hearing thunder — even though both happen simultaneously.", fact: "Light travels at ~300,000 km/s and needs no medium. Sound travels at 343 m/s through air and cannot travel through space. Every 3 seconds between lightning and thunder = ~1 km distance.", tip: "🧠 3 seconds = 1 km away. Count the gap, divide by 3. Works every time." },
  { id: 's8', cat: 'science', emoji: '🌍', subject: 'Science — Gravity', diff: 1, hook: "It holds you to the floor, the Moon in orbit, and galaxies together.", fact: "Gravity is an attractive force between any two objects with mass. Earth's gravity pulls at 9.8 m/s² downward. The Moon's gravity is 1/6 of Earth's — why astronauts bounce. Gravity is the weakest fundamental force but acts across unlimited range.", tip: "🧠 Moon gravity = 1/6 Earth. 80kg on Earth = 13kg on Moon. Same mass, different weight." },
  { id: 's9', cat: 'science', emoji: '🧬', subject: 'Science — DNA', diff: 2, hook: "Every cell contains a 2-metre instruction manual folded into a space you can't see.", fact: "Human DNA is ~2 metres long when uncoiled, yet fits inside a cell nucleus just 6 micrometres wide. It contains ~3 billion base pairs. You share 99.9% of DNA with every other human — and 60% with a banana.", tip: "🧠 You share 99.9% DNA with all humans. 60% with a banana. The 0.1% = all human diversity." },
  { id: 's10', cat: 'science', emoji: '🌌', subject: 'Science — Universe', diff: 2, hook: "The universe is 13.8 billion years old — but 93 billion light-years wide. Both are true.", fact: "The universe is 13.8 billion years old. But it's 93 billion light-years wide because space itself expanded faster than light during early inflation. There are an estimated 2 trillion galaxies, each with hundreds of billions of stars.", tip: "🧠 Age: 13.8 billion years. Width: 93 billion light-years. Space expands faster than light travels." },

  // HISTORY
  { id: 'h1', cat: 'history', emoji: '⚔️', subject: 'History — WW1', diff: 1, hook: "One bullet in Sarajevo in 1914 dragged the entire world into war.", fact: "World War One (1914–1918) was triggered by the assassination of Archduke Franz Ferdinand on 28 June 1914. The real causes were rival alliances, imperial competition, and arms races. Around 20 million people died.", tip: "🧠 The assassination was the spark. The powder keg — alliances, empire, rivalry — was already built." },
  { id: 'h2', cat: 'history', emoji: '🏛️', subject: 'History — Ancient Rome', diff: 1, hook: "Rome ruled the world for over 1,000 years and we still live inside its legacy.", fact: "Rome was a republic for ~500 years before becoming an Empire in 27 BC under Augustus. The Western Empire fell in 476 AD. Rome gave the world roads, concrete, aqueducts, Roman law, the Latin alphabet, and our 12-month calendar.", tip: "🧠 Republic → Empire: 27 BC. 'Calendar', 'senate', 'virus', 'justice' all come from Latin." },
  { id: 'h3', cat: 'history', emoji: '🌍', subject: 'History — Cold War', diff: 2, hook: "The most dangerous standoff in history — not a single direct shot was fired.", fact: "The Cold War (1947–1991) pitted the USA against the USSR. They never fought directly but competed through proxy wars (Korea, Vietnam), nuclear arms racing, and the Space Race. The Cuban Missile Crisis of 1962 brought the world within minutes of nuclear war.", tip: "🧠 Cuban Missile Crisis = closest to nuclear war. Cold = no direct combat. Proxy wars = fighting through other countries." },
  { id: 'h4', cat: 'history', emoji: '🎨', subject: 'History — Renaissance', diff: 1, hook: "It began in one Italian city and rewrote the intellectual history of all Europe.", fact: "The Renaissance ('rebirth') began in Florence, Italy in the 14th century. The Medici banking family funded artists and scientists. Leonardo da Vinci, Michelangelo, Galileo, and Raphael all emerged from this era.", tip: "🧠 Renaissance = rebirth. Florence. Medici funded it. Da Vinci was artist AND scientist AND engineer." },
  { id: 'h5', cat: 'history', emoji: '🧭', subject: 'History — Exploration', diff: 1, hook: "He was trying to reach Asia. He found a continent he didn't know existed.", fact: "In 1492, Columbus — sailing for Spain — reached the Caribbean. He believed he'd found Asia and called the locals 'Indians'. The Americas were named after Amerigo Vespucci, who confirmed it was a new continent.", tip: "🧠 Columbus: thought it was Asia. Vespucci: realised it was new. America named after Amerigo, not Columbus." },
  { id: 'h6', cat: 'history', emoji: '💣', subject: 'History — WW2', diff: 1, hook: "The deadliest conflict in human history lasted just six years.", fact: "WW2 (1939–1945) killed 70–85 million people — ~3% of world population. It ended in Europe on VE Day (8 May 1945) and in the Pacific on VJ Day (15 Aug 1945) after atomic bombs hit Hiroshima (6 Aug) and Nagasaki (9 Aug).", tip: "🧠 VE Day = May 8. VJ Day = Aug 15. Hiroshima = Aug 6. Nagasaki = Aug 9." },
  { id: 'h7', cat: 'history', emoji: '🚀', subject: 'History — Space Race', diff: 1, hook: "On 20 July 1969, a human stood on another world for the very first time.", fact: "Apollo 11 landed on the Moon on 20 July 1969. Neil Armstrong was first on the surface; Buzz Aldrin followed minutes later. Michael Collins orbited above and never landed — the most overlooked astronaut in history.", tip: "🧠 Armstrong first. Aldrin second. Collins orbited — never landed. The forgotten third astronaut." },
  { id: 'h8', cat: 'history', emoji: '👩‍💻', subject: 'History — Famous Firsts', diff: 2, hook: "The world's first computer programmer wrote code in the 1840s — a century before computers existed.", fact: "Ada Lovelace (1815–1852) wrote the first algorithm intended for a machine — Babbage's proposed Analytical Engine. She was the daughter of poet Lord Byron. The programming language 'Ada' is named after her.", tip: "🧠 Ada Lovelace = first programmer, 1840s. Daughter of Lord Byron. The language 'Ada' is named after her." },

  // GEOGRAPHY
  { id: 'geo1', cat: 'geo', emoji: '🌍', subject: 'Geography — Continents', diff: 1, hook: "Most people name 5 easily. The last two always trip someone up.", fact: "7 continents: Africa, Antarctica, Asia, Australia/Oceania, Europe, North America, South America. Asia is largest (44M km²) and most populated (60% of world population). Antarctica has zero permanent residents.", tip: "🧠 Memory: Eat An Apple As A Night Snack → Europe, Antarctica, Asia, Africa, Australia, N.America, S.America." },
  { id: 'geo2', cat: 'geo', emoji: '🌊', subject: 'Geography — Oceans', diff: 1, hook: "One ocean is larger than every piece of land on Earth put together.", fact: "5 oceans: Pacific (largest — bigger than all land combined), Atlantic, Indian, Southern, Arctic (smallest). Together they cover ~71% of Earth. The Pacific contains more than half of all ocean water.", tip: "🧠 Size order: Pacific, Atlantic, Indian, Southern, Arctic. Mnemonic: PAISA." },
  { id: 'geo3', cat: 'geo', emoji: '⛰️', subject: 'Geography — Mountains', diff: 2, hook: "The tallest mountain depends entirely on how you measure it.", fact: "Everest (8,849m) = highest above sea level. Mauna Kea in Hawaii = tallest base to summit (~10,200m, mostly underwater). Chimborazo in Ecuador = furthest from Earth's centre. Three records, three mountains.", tip: "🧠 Everest: altitude. Mauna Kea: total height. Chimborazo: from Earth's core. All three are correct." },
  { id: 'geo4', cat: 'geo', emoji: '🌐', subject: 'Geography — Navigation', diff: 1, hook: "Every GPS system runs on a coordinate grid invented centuries before satellites.", fact: "Latitude = east–west lines measuring north/south from the equator (0°). Longitude = north–south lines from the Prime Meridian in Greenwich, London (0°). Together they pinpoint any location on Earth.", tip: "🧠 Lat = flat/horizontal. Long = tall/vertical (pole to pole). Equator = 0° lat. Greenwich = 0° long." },
  { id: 'geo5', cat: 'geo', emoji: '🌋', subject: 'Geography — Geology', diff: 2, hook: "The ground beneath your feet is moving right now — just very slowly.", fact: "Earth's crust is divided into ~15 major tectonic plates drifting a few cm per year. Plates colliding = mountains. Plates separating = rift valleys and volcanoes. Plates sliding = earthquakes. The Himalayas grow ~5mm per year.", tip: "🧠 Collide = mountains. Separate = rifts. Slide = earthquakes. Three boundary types, three outcomes." },
  { id: 'geo6', cat: 'geo', emoji: '🗺️', subject: 'Geography — Rivers', diff: 2, hook: "Two great rivers hold two different world records.", fact: "The Nile (≈6,650km) is generally the world's longest river. The Amazon (≈6,400km) carries ~20% of all freshwater entering the world's oceans — more than the next 7 largest rivers combined.", tip: "🧠 Nile = longest. Amazon = most water volume (20% of global river discharge)." },

  // HUMAN BODY
  { id: 'b1', cat: 'body', emoji: '🫀', subject: 'Body — Heart', diff: 1, hook: "It has never once stopped beating in your entire life.", fact: "The heart beats ~100,000 times/day, 35 million/year, 2.5 billion in a lifetime. It pushes blood through ~100,000km of vessels. The left side pumps oxygenated blood to the body; the right pumps deoxygenated blood to the lungs.", tip: "🧠 Left = oxygenated OUT to body. Right = deoxygenated IN from body → lungs. Left = Life." },
  { id: 'b2', cat: 'body', emoji: '🧠', subject: 'Body — Brain', diff: 2, hook: "Your brain is cross-wired: left controls right, right controls left — always.", fact: "~86 billion neurons in the brain. Left hemisphere controls the right side of the body and handles language. Right hemisphere controls the left side and handles creativity. The brain uses ~20% of your body's total energy.", tip: "🧠 Left brain = right body + language. Right brain = left body + creativity. 20% of your energy." },
  { id: 'b3', cat: 'body', emoji: '🫁', subject: 'Body — Lungs', diff: 1, hook: "Your two lungs are deliberately different sizes — not a design flaw.", fact: "Right lung = 3 lobes. Left lung = 2 lobes — smaller to make room for the heart. At rest: ~15 breaths/minute, ~6 litres/minute, over 8,000 litres/day. Gas exchange happens in ~480 million tiny alveoli.", tip: "🧠 Right = 3 lobes. Left = 2 (heart takes space). 480 million alveoli unfolded = tennis court." },
  { id: 'b4', cat: 'body', emoji: '🦴', subject: 'Body — Bones', diff: 1, hook: "You had more bones as a baby — they fused as you grew.", fact: "Adults = 206 bones. Babies = ~270 (fuse by age 25). Bones are living tissue — they constantly rebuild and produce blood cells in marrow. Femur = longest and strongest. Stapes in the ear = smallest at 3mm.", tip: "🧠 206 adult bones. 270 at birth. Femur = longest. Stapes = smallest. Bone is stronger than steel by weight." },
  { id: 'b5', cat: 'body', emoji: '🩸', subject: 'Body — Blood', diff: 1, hook: "That red stuff is doing four completely different jobs simultaneously.", fact: "Blood = red cells (carry O₂) + white cells (fight infection) + platelets (clot wounds) + plasma (transport nutrients). Adults have ~5 litres. Red cells live 120 days. Your body makes 2 million new red cells every second.", tip: "🧠 Red = oxygen. White = defence. Platelets = plug leaks. Plasma = the river. 2M new red cells/second." },
  { id: 'b6', cat: 'body', emoji: '👁️', subject: 'Body — Eyes', diff: 2, hook: "The image your eye sends your brain right now is upside-down.", fact: "Eyes distinguish ~10 million colours. The retina captures images inverted; the brain flips them instantly. Each eye has a blind spot where the optic nerve connects — the brain fills this gap seamlessly.", tip: "🧠 Blind spot test: close one eye, focus ahead, slowly move a finger from the side — it disappears." },
  { id: 'b7', cat: 'body', emoji: '🦠', subject: 'Body — Microbiome', diff: 2, hook: "You are outnumbered — bacteria cells match your human cells in number.", fact: "Your gut contains ~38 trillion bacteria — equal to your total human cell count. These bacteria aid digestion, produce vitamins K and B12, regulate immunity, and influence mood via the gut-brain axis.", tip: "🧠 38 trillion gut bacteria = your human cell count. Gut health affects mood. Antibiotics kill the good too." },
  { id: 'b8', cat: 'body', emoji: '😴', subject: 'Body — Sleep', diff: 1, hook: "You spend a third of your life unconscious — and you'd die faster without it than without food.", fact: "Humans need 7–9 hours of sleep. During sleep: the brain consolidates memories, tissue repairs, and the glymphatic system flushes toxic waste including Alzheimer's-linked proteins. REM sleep handles emotional processing.", tip: "🧠 Sleep clears brain toxins. You die faster without sleep than food. REM = emotional health." },

  // GRAMMAR
  { id: 'g1', cat: 'grammar', emoji: '✍️', subject: 'Grammar — Apostrophes', diff: 1, hook: "One tiny mark that millions of people use wrong every single day.", fact: "Apostrophes do two jobs: possession (Sarah's bag) and contractions (don't = do not). Never for plurals. 'It's' always means 'it is'. 'Its' without apostrophe is the possessive form.", tip: "🧠 Before writing an apostrophe: ownership or shortening? No to both = no apostrophe." },
  { id: 'g2', cat: 'grammar', emoji: '📝', subject: "Grammar — Their/There/They're", diff: 1, hook: "Three words, one sound, three completely different meanings.", fact: "Their = belonging to them. There = a location. They're = they are. Test: say 'they are' out loud. If it works, use they're. If it breaks, choose their or there based on ownership vs location.", tip: "🧠 They're → replace with 'they are'. Works = they're. Doesn't = their (ownership) or there (place)." },
  { id: 'g3', cat: 'grammar', emoji: '💬', subject: 'Grammar — Active vs Passive', diff: 2, hook: "Professional writers default to one of these. Weak writing defaults to the other.", fact: "Active voice: subject performs the action — direct and strong. 'The dog bit the man.' Passive voice: subject receives the action — wordier. 'The man was bitten by the dog.' Passive also hides responsibility: 'Mistakes were made.'", tip: "🧠 Zombie test: add 'by zombies' after the verb. Works = passive. Rewrite as active." },
  { id: 'g4', cat: 'grammar', emoji: '❓', subject: 'Grammar — Who vs Whom', diff: 3, hook: "Even confident native speakers get this wrong.", fact: "'Who' = subject (performs action). 'Whom' = object (receives action). Trick: substitute 'he' or 'him'. If 'he' fits → use who. If 'him' fits → use whom. Who/he = subjects. Whom/him = objects.", tip: "🧠 He = who. Him = whom. Whom and Him both end in M — the memory trick that always works." },
  { id: 'g5', cat: 'grammar', emoji: '📖', subject: 'Grammar — Semicolons', diff: 2, hook: "The most misunderstood punctuation mark in English.", fact: "A semicolon joins two complete, related sentences without a conjunction. 'I was exhausted; I went straight to bed.' Both sides must work as standalone sentences. Never use it between incomplete and complete clauses.", tip: "🧠 Semicolon = soft stop. Both sides = complete sentences. Test: read each side alone. Both work? Use it." },

  // PSYCHOLOGY
  { id: 'psy1', cat: 'psychology', emoji: '🧠', subject: 'Psychology — Bias', diff: 2, hook: "You are far more irrational than you believe — science has proved it.", fact: "Confirmation bias: the tendency to seek and favour information confirming existing beliefs, while ignoring contradictory evidence. It affects everyone regardless of intelligence. Social media algorithms exploit it deliberately.", tip: "🧠 Confirmation bias: believe first, find 'proof' second. Antidote: actively seek evidence against your own position." },
  { id: 'psy2', cat: 'psychology', emoji: '😊', subject: 'Psychology — Happiness', diff: 1, hook: "Money buys happiness — but only up to a precise point.", fact: "Research found emotional wellbeing increases with income up to ~$100,000/year, after which daily happiness plateaus. However, life satisfaction — how you evaluate your life overall — continues increasing with wealth beyond that.", tip: "🧠 Day-to-day happiness: plateaus ~$100k. Life satisfaction: keeps rising. Two different types of happy." },
  { id: 'psy3', cat: 'psychology', emoji: '👥', subject: 'Psychology — Obedience', diff: 2, hook: "65% of ordinary people will harm someone if an authority figure tells them to.", fact: "Stanley Milgram's experiments (1961) showed 65% of participants would administer what they believed were dangerous electric shocks simply because a scientist instructed them. The study revealed how powerfully authority overrides ethics.", tip: "🧠 Milgram: 65% harmed someone on authority's orders. Explains how ordinary people participate in atrocities." },
  { id: 'psy4', cat: 'psychology', emoji: '🎯', subject: 'Psychology — Memory', diff: 1, hook: "Your memory is not a recording — it gets things wrong every time you access it.", fact: "Human memory is reconstructive, not reproductive. Every retrieval slightly alters the memory. Eyewitness testimony is notoriously unreliable. Elizabeth Loftus demonstrated that false memories can be implanted through suggestion alone.", tip: "🧠 Memory ≠ video playback. It rebuilds each time and changes slightly. 'I clearly remember' ≠ accurate." },
  { id: 'psy5', cat: 'psychology', emoji: '🌊', subject: 'Psychology — Flow', diff: 1, hook: "Athletes call it 'the zone'. Psychologists have studied it for decades.", fact: "'Flow' (coined by Csikszentmihalyi) is complete absorption in a challenging task where time distorts and performance peaks. It occurs when skill and difficulty closely match — too easy = boredom, too hard = anxiety.", tip: "🧠 Flow = skill matches challenge. Boredom = too easy. Anxiety = too hard. Sweet spot = peak performance." },
  { id: 'psy6', cat: 'psychology', emoji: '😴', subject: 'Psychology — Dreams', diff: 2, hook: "You forget 90% of your dreams within 10 minutes of waking up.", fact: "Dreaming occurs primarily during REM sleep. The average person has 4–6 dreams per night but forgets almost all. The prefrontal cortex is less active during REM, so memory encoding is weak — dreams evaporate quickly.", tip: "🧠 Write dreams down immediately on waking — within 2 minutes. After 10 minutes, 90% is gone permanently." },

  // ECONOMICS
  { id: 'eco1', cat: 'economics', emoji: '💰', subject: 'Economics — Inflation', diff: 1, hook: "Your money is losing value right now — even sitting still in your wallet.", fact: "Inflation = the rate at which prices rise, reducing purchasing power. If inflation is 5%, something costing €100 last year costs €105 today. Central banks target ~2% annual inflation as healthy for a growing economy.", tip: "🧠 Inflation = money buys less over time. 2% = healthy. Above 5% = problem. Cash idle loses value yearly." },
  { id: 'eco2', cat: 'economics', emoji: '📈', subject: 'Economics — Supply & Demand', diff: 1, hook: "Every price you've ever paid was determined by this one law.", fact: "Supply up + demand same = prices fall. Demand up + supply same = prices rise. This law of supply and demand underpins all market economics — from house prices to concert tickets to petrol.", tip: "🧠 Scarce + wanted = expensive. Abundant + unwanted = cheap. Every market price = supply meeting demand." },
  { id: 'eco3', cat: 'economics', emoji: '🏦', subject: 'Economics — Interest Rates', diff: 2, hook: "When central banks change one number, every mortgage on Earth is affected.", fact: "Central banks set base interest rates — the cost of borrowing. Higher rates = expensive loans = less spending = inflation cools. Lower rates = cheap borrowing = more spending = economic stimulus.", tip: "🧠 Rates up = borrowing costs more = less spending = inflation drops. Rates down = more growth." },
  { id: 'eco4', cat: 'economics', emoji: '📊', subject: 'Economics — GDP', diff: 1, hook: "One number attempts to measure the entire economic output of a country.", fact: "GDP = total monetary value of all goods and services produced in a country per year. USA leads (~$27 trillion), China is second (~$18 trillion). Two consecutive quarters of shrinking GDP = recession.", tip: "🧠 GDP shrinks 2 quarters in a row = recession (official definition). USA: ~$27T. China: ~$18T." },
  { id: 'eco5', cat: 'economics', emoji: '💸', subject: 'Economics — Compound Interest', diff: 1, hook: "Einstein allegedly called this the eighth wonder of the world.", fact: "Compound interest = earning interest on principal AND previously earned interest. €1,000 at 7% annual return doubles to €2,000 in ~10 years, €4,000 in 20, €8,000 in 30 — without adding a cent.", tip: "🧠 Rule of 72: divide 72 by the interest rate = years to double. 72 ÷ 7% = ~10 years to double." },

  // INVENTIONS
  { id: 'inv1', cat: 'inventions', emoji: '💡', subject: 'Inventions — Light Bulb', diff: 1, hook: "Thomas Edison did not invent the light bulb — he commercialised it.", fact: "Humphry Davy demonstrated electric light in 1802. Joseph Swan patented a working bulb in Britain in 1878. Edison patented his improved version in 1879 and built the entire electrical distribution infrastructure to make it practical.", tip: "🧠 Edison: didn't invent the bulb, made it practical, built the grid. The system was the innovation." },
  { id: 'inv2', cat: 'inventions', emoji: '🌐', subject: 'Inventions — Internet vs Web', diff: 1, hook: "The internet and the World Wide Web are not the same thing.", fact: "The internet originated from ARPANET in 1969. The World Wide Web — websites and browsers — was invented by Tim Berners-Lee in 1989 at CERN. The web runs on the internet, but the internet existed 20 years before the web.", tip: "🧠 Internet = infrastructure (1969). Web = websites (1989). Berners-Lee invented the Web, not the internet." },
  { id: 'inv3', cat: 'inventions', emoji: '✈️', subject: 'Inventions — Flight', diff: 1, hook: "The Wright Brothers' first flight covered less than the wingspan of a Boeing 747.", fact: "The Wright Brothers achieved the first powered flight on 17 December 1903 at Kitty Hawk. It lasted 12 seconds and covered 37 metres. A Boeing 747 wingspan is 68 metres. They were bicycle mechanics with no engineering degrees.", tip: "🧠 First flight: 1903, 12 seconds, 37 metres. 747 wingspan > entire first flight. Bicycle mechanics." },
  { id: 'inv4', cat: 'inventions', emoji: '💊', subject: 'Inventions — Penicillin', diff: 1, hook: "One of medicine's greatest discoveries happened because a scientist left a dish dirty.", fact: "Alexander Fleming discovered penicillin in 1928 when mould contaminated a bacteria culture and killed surrounding bacteria. He noticed and investigated. Penicillin mass-produced in WW2 has since saved over 200 million lives.", tip: "🧠 Fleming, 1928, accidental discovery. 200 million lives saved. The lucky dirty dish changed medicine." },
  { id: 'inv5', cat: 'inventions', emoji: '🖨️', subject: 'Inventions — Printing Press', diff: 2, hook: "One machine in 1440 directly caused the Renaissance, the Reformation, and the Scientific Revolution.", fact: "Gutenberg invented the movable-type printing press around 1440. Before it, books were hand-copied and expensive. Within 50 years, over 20 million books circulated across Europe. Mass literacy and the spread of ideas trace back to this machine.", tip: "🧠 Gutenberg press: 1440. Before: books = luxury. After: ideas at scale. The internet of the 15th century." },
  { id: 'inv6', cat: 'inventions', emoji: '🧲', subject: 'Inventions — Radio', diff: 2, hook: "Marconi is credited with inventing radio — but a court ruled someone else did it first.", fact: "Marconi sent the first transatlantic radio signal in 1901. But the US Supreme Court ruled in 1943 that Nikola Tesla's earlier patents predated Marconi's core claims. The ruling came months after Tesla's death.", tip: "🧠 Marconi: credited with radio, 1901. Tesla: original patents, 1893. Court ruled for Tesla after he died." },

  // FOOD SCIENCE
  { id: 'food1', cat: 'food', emoji: '🍕', subject: 'Food Science — Taste', diff: 1, hook: "Your nose does about 80% of the tasting — your tongue only contributes 20%.", fact: "Humans have 5 basic tastes: sweet, salty, sour, bitter, and umami. But ~80% of what we perceive as flavour is actually smell. This is why food tastes bland with a blocked nose. Flavour = taste + smell + texture.", tip: "🧠 5 tastes: sweet, salty, sour, bitter, umami. Block nose while eating = almost no flavour. Taste ≠ flavour." },
  { id: 'food2', cat: 'food', emoji: '🌶️', subject: 'Food Science — Spice', diff: 1, hook: "Chilli heat isn't a taste — it's literally pain.", fact: "Capsaicin in chillies triggers TRPV1 pain receptors, not taste receptors. The brain releases endorphins in response — why spicy food feels addictive. Milk neutralises capsaicin (fat-soluble). Water spreads it (not water-soluble).", tip: "🧠 Spice = pain receptors, not taste. Milk kills the burn. Water spreads it. Endorphins = the spicy high." },
  { id: 'food3', cat: 'food', emoji: '🍫', subject: 'Food Science — Chocolate', diff: 1, hook: "White chocolate technically isn't chocolate at all.", fact: "Dark and milk chocolate contain cocoa solids — ground cacao. White chocolate contains only cocoa butter, sugar, and milk — zero cocoa solids. Dark chocolate (70%+) contains flavanols that measurably improve cardiovascular health.", tip: "🧠 White chocolate = no cocoa solids = not really chocolate. Dark 70%+ = real health benefits." },
  { id: 'food4', cat: 'food', emoji: '🥑', subject: 'Food Science — Ethylene', diff: 2, hook: "Putting a banana next to an avocado makes it ripen faster — there's a scientific reason.", fact: "Many fruits produce ethylene gas as they ripen, triggering ripening in nearby fruit. Bananas are high ethylene emitters. Sealing an unripe avocado with a banana speeds ripening. Keeping bananas away from other fruit slows their ripening.", tip: "🧠 Ethylene = ripening gas. Banana with avocado = faster ripe. Store bananas separately to slow ripening." },
  { id: 'food5', cat: 'food', emoji: '☕', subject: 'Food Science — Caffeine', diff: 1, hook: "Caffeine doesn't give you energy — it just blocks the signal that tells you you're tired.", fact: "Caffeine blocks adenosine receptors. Adenosine builds up throughout the day and signals tiredness. Caffeine blocks the same receptors so fatigue signals can't reach the brain. When it wears off, the adenosine floods back — the crash.", tip: "🧠 Caffeine blocks tiredness — doesn't create energy. The crash = adenosine flood when caffeine clears." },
  { id: 'food6', cat: 'food', emoji: '🍞', subject: 'Food Science — Fermentation', diff: 2, hook: "Bread dough is alive — right up until you put it in the oven.", fact: "Leavened bread uses yeast — a living microorganism. Yeast consumes dough sugars and produces CO₂ and alcohol. CO₂ bubbles cause the dough to rise. The oven kills the yeast. Beer and bread use identical biology.", tip: "🧠 Yeast eats sugar → CO₂ + alcohol → dough rises → oven kills yeast → bread. Same process as beer." },

  // MATHS
  { id: 'm1', cat: 'math', emoji: '♾️', subject: 'Maths — Infinity', diff: 3, hook: "Not all infinities are equal — mathematicians proved this rigorously.", fact: "There are different sizes of infinity. The set of whole numbers is infinite, but the set of all decimals between just 0 and 1 is a provably larger infinity. Georg Cantor demonstrated this in the 1870s. His peers called him a 'corruptor of youth'. He was later proved completely right.", tip: "🧠 Whole number infinity < decimal infinity. Even 'forever' has different sizes. Cantor proved it." },
  { id: 'm2', cat: 'math', emoji: '🔢', subject: 'Maths — Zero', diff: 2, hook: "Ancient Romans could conquer the world but couldn't do arithmetic we teach 8-year-olds.", fact: "Zero was developed in India (~5th century AD) and transmitted to Europe via Arab mathematicians. Without zero, positional number systems (10, 100, 1000) collapse. Roman numerals had no zero, making multiplication and division incredibly cumbersome.", tip: "🧠 Try XIV × IX in Roman numerals. It's a nightmare. Zero made modern maths, banking, and computing possible." },
  { id: 'm3', cat: 'math', emoji: '🌀', subject: 'Maths — Golden Ratio', diff: 2, hook: "One number appears in sunflowers, nautilus shells, the Parthenon, and Renaissance paintings.", fact: "The golden ratio (φ ≈ 1.618) appears throughout nature and art. Sunflower seed spirals, nautilus shells, and the Parthenon's proportions all approximate phi. Your height divided by your navel height is approximately 1.618.", tip: "🧠 φ ≈ 1.618. Height ÷ navel height ≈ golden ratio. Nature finds this proportion structurally efficient." },
  { id: 'm4', cat: 'math', emoji: '🎲', subject: 'Maths — Probability', diff: 2, hook: "Every properly shuffled deck is almost certainly unique in the history of the universe.", fact: "52! (52 factorial) = possible deck arrangements = a 68-digit number dwarfing atoms on Earth (~10⁵⁰). If every person ever shuffled a deck every second since the Big Bang, they'd cover a vanishingly small fraction of arrangements.", tip: "🧠 52! ≈ 8×10⁶⁷. Atoms on Earth ≈ 10⁵⁰. Your shuffled deck is almost certainly unprecedented in history." },
  { id: 'm5', cat: 'math', emoji: '📐', subject: 'Maths — Pythagoras', diff: 1, hook: "A theorem from 570 BC is still used in GPS, architecture, and video game engines today.", fact: "In any right-angled triangle: a² + b² = c² (c = hypotenuse). Classic: 3² + 4² = 5². Works every time without exception. Used in construction, navigation, 3D graphics, physics, and GPS. Also: Pythagoras banned his followers from eating beans.", tip: "🧠 Classic triples: 3-4-5, 5-12-13, 8-15-17. Pythagoras also banned beans. Both facts may appear in a quiz." },
];
